### ISSUE TITLE
THREE's renderer and scene could be represented as nodes

### ISSUE THREAD

**Issue by frading** [polygonjs/polygonjs-engine#8]
Currently the camera creates its own renderer, and every node is added to the same scene. Having dedicated nodes for each would allow to:

-   more easily change the parameters of a renderers
-   choose which scene an object is added to, which could help doing post processing after having rendered multiple scenes

**Comment by polygonjs** [comment]
a Renderer node context has been added: https://polygonjs.com/docs/nodes/rop. It is currently possible to create a WebGLRenderer node, and edit the same parameters as the THREE.WebGLRenderer. There is also a Css2DRenderer to add HTML labels.

The rendered scene can be set as a parameter on the camera node, such as on the [PerspectiveCamera](https://polygonjs.com/docs/nodes/obj/PerspectiveCamera) or [OrthographicCamera](https://polygonjs.com/docs/nodes/obj/OrthographicCamera).
